baseURL = "http://cantyouju.st/"
languageCode = "en-us"
title = "Can't you just?"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = ''
  logo = "fas fa-gem"
  copyright = "CantYouJu.st"

weight = 1
